# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblogs", "0006_auto_20170405_1445"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="allow_comments",
            field=models.BooleanField(
                default=True,
                help_text="If true, can still be overridden in Django SETTINGS.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(
                default=True,
                help_text="If true, can still be overridden by the Blog's equivalent setting, or in Django SETTINGS.",  # noqa: E501
            ),
        ),
    ]
