# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weblogs", "0012_auto_20170929_1509"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trackback", unique_together=set([("post", "url")]),
        ),
    ]
