# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblogs", "0013_auto_20170929_1529"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="trackback_count",
            field=models.IntegerField(default=0),
        ),
    ]
