# Generated by Django 2.0.1 on 2018-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogs', '0015_auto_20180107_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (4, 'Scheduled')], default=1),
        ),
    ]
