# Generated by Django 2.1.3 on 2018-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblogs", "0016_auto_20180516_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time_published",
            field=models.DateTimeField(null=True),
        ),
    ]
