# Generated by Django 2.2.1 on 2019-05-31 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weblogs", "0019_auto_20190531_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time_published",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
