# Generated by Django 2.2.6 on 2019-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblogs", "0021_auto_20190721_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="html_format",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No formatting"),
                    (1, "Convert line breaks"),
                    (2, "Markdown"),
                    (3, "Hines Markdown"),
                ],
                default=3,
                verbose_name="HTML format",
            ),
        ),
    ]
