# Generated by Django 3.2.9 on 2021-11-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogs', '0024_auto_20210408_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_incoming_webmentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_outgoing_webmentions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='incoming_webmention_count',
            field=models.IntegerField(default=0),
        ),
    ]
