# Generated by Django 3.2.9 on 2021-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogs', '0025_auto_20211124_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='allow_incoming_webmentions',
            field=models.BooleanField(default=True, help_text='If true, can still be overridden in Django SETTINGS.'),
        ),
        migrations.AddField(
            model_name='blog',
            name='allow_outgoing_webmentions',
            field=models.BooleanField(default=True, help_text='If true, can still be overridden in Django SETTINGS.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='allow_incoming_webmentions',
            field=models.BooleanField(default=True, help_text="If true, can still be overridden by the Blog's equivalent setting, or in Django SETTINGS."),
        ),
        migrations.AlterField(
            model_name='post',
            name='allow_outgoing_webmentions',
            field=models.BooleanField(default=False, help_text="If true, can still be overridden by the Blog's equivalent setting, or in Django SETTINGS."),
        ),
    ]
