# Generated by Django 4.1.1 on 2022-10-01 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weblogs", "0026_post_allow_incoming_webmentions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="allow_incoming_webmentions",
        ),
    ]
