# Generated by Django 3.2.9 on 2021-11-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogs', '0026_auto_20211124_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allow_outgoing_webmentions',
            field=models.BooleanField(default=True, help_text="If true, can still be overridden by the Blog's equivalent setting, or in Django SETTINGS."),
        ),
    ]
