# Generated by Django 4.1.3 on 2022-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblogs", "0027_remove_post_allow_incoming_webmentions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="allow_outgoing_webmentions",
            field=models.BooleanField(
                default=False,
                verbose_name="allow outgoing webmentions",
            ),
        ),
    ]
