default_language_version:
  python: python3.10

exclude: |
  (?x)^(
    assets/css/vendor/.*
    |assets/js/vendor/.*
    |hines/static/.*
    |hines/static_html/.*
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Use locally-installed npm version of Biome
  # So we don't have to update npm AND pre-commit version when updating Biome
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
