default_language_version:
  python: python3.10

exclude: |
  (?x)^(
    assets/css/vendor/.*
    |assets/js/vendor/.*
    |hines/static/.*
    |hines/static_html/.*
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or:
          - css
          - javascript
          - json
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
