dist: trusty
language: python
python:
  - "3.6"
services:
  - postgresql
branches:
  only:
  - master
env:
  - DJANGO_SECRET_KEY="fake-secret-key-for-tests"
  - DB_NAME='test_db'
  - DB_USER='postgres'
  - DB_PASSWORD=''
  - DB_HOST='localhost'
#matrix:
  #include:
    #- python: "3.6"
install:
  - pip install coverage coveralls
  - pip install -r ./requirements/tests.txt
before_script:
  - ./manage.py collectstatic --noinput --settings=config.settings.tests --verbosity=0
  - psql -c 'CREATE DATABASE test_db;' -U postgres
script:
  - ./scripts/run-tests.sh
after_success:
  - coveralls
sudo: false

