dist: trusty
language: python
python:
  - "3.6"
branches:
  only:
  - master
env:
  - DJANGO=1.11
matrix:
  include:
    - python: "3.6"
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - ./scripts/run-tests.sh
after_success:
  - coveralls
sudo: false

