dist: trusty
language: python
python:
  - "3.6"
services:
  - postgresql
branches:
  only:
  - master
env:
  global:
    - DJANGO_SECRET_KEY="fake-secret-key-for-tests"
    - DB_NAME='test_db'
    - DB_USERNAME='postgres'
    - DB_PASSWORD=''
    - DB_HOST='localhost'
install:
  - pip install -q coverage coveralls
  - pip install -q -r ./requirements/tests.txt
before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - ./manage.py migrate --settings=config.settings.tests --verbosity=0
  - ./manage.py collectstatic --settings=config.settings.tests --verbosity=0 --noinput 
script:
  - ./scripts/run-tests.sh
after_success:
  - coveralls
sudo: false

