language: python
python:
  - "3.6.3"
branches:
  only:
  - master
env:
  - DJANGO=1.11
matrix:
  include:
    - python: "3.6.3"
install:
  - pip install coverage coveralls
script:
  - ./scripts/run-tests.sh
after_success:
  - coveralls
sudo: false

