dist: trusty
language: python
python:
  - "3.6"
branches:
  only:
  - master
env:
  - DJANGO_SECRET_KEY="fake-secret-key-for-tests"
matrix:
  include:
    - python: "3.6"
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - ./manage.py collectstatic --noinput --settings=config.settings.tests
  - ./scripts/run-tests.sh
after_success:
  - coveralls
sudo: false

