# For use in development only.

services:
  assets:
    build:
      context: .
      dockerfile: ./docker/assets/Dockerfile
    command: sh -c "yarn && yarn watch"
    container_name: hines_assets
    volumes:
      - .:/code
      # HACK: use node_modules from inside image instead of one on local machine
      - /code/node_modules

  db:
    container_name: hines_db
    env_file: .env
    image: postgres:13
    # Uncomment this and restart to log all queries to the console:
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5555:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: hines_redis
    deploy:
      resources:
        limits:
          # When set to 0 these will use as much as needed:
          cpus: "0"
          memory: "0"
    image: "redis:7-bullseye"
    ports:
      - "6666:6379"
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "redis:/data"

volumes:
  postgres_data:
  redis:
