version: '3.9'

# For use in development only.

services:
  # Postgres
  db:
    container_name: hines_db
    env_file: .env
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # Redis
  # redis:
  #   restart: always
  #   image: sameersbn/redis:4.0.9-2  # Or redis:alpine?
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./docker/redis:/var/lib/redis:delegated
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}

  # Application
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: >
      sh -c "
      pipenv run python manage.py migrate &&
      pipenv run python -Wd manage.py runserver 0.0.0.0:8000
      "
    container_name: hines_web
    depends_on:
      - db
      # - redis
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/code

volumes:
  postgres_data: