# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_comments", "0003_add_submit_date_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomComment",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("django_comments.comment",),
        ),
    ]
