# Generated by Django 3.2.9 on 2021-11-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingWebmention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('object_pk', models.PositiveIntegerField()),
                ('source_url', models.URLField(blank=True, help_text='ULR of the object on this site that sent the webmention.')),
                ('target_url', models.URLField(blank=True, help_text='The URL that was mentioned.')),
                ('target_endpoint_url', models.URLField(blank=True, help_text='The endpoint URL to which we sent the webmention.', null=True)),
                ('status', models.CharField(choices=[('WA', 'Waiting to be sent'), ('UN', 'Target URL is unreachable'), ('TE', 'Target URL returned an error'), ('EE', 'Endpoint URL returned an error'), ('OK', 'Target accepted the webmention')], default='WA', max_length=2)),
                ('response_code', models.PositiveIntegerField(default=None, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='IncomingWebmention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('object_pk', models.PositiveIntegerField()),
                ('source_title', models.CharField(blank=True, help_text='Title of the page that sent the webmention.', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Source address of the HTTP request that sent this webmention.')),
                ('target_url', models.URLField(blank=True, help_text='URL of the object on this site that the mention was sent to.')),
                ('is_public', models.BooleanField(default=False, help_text='Allow this to appear publicly')),
                ('source_is_deleted', models.BooleanField(default=False, help_text='Has the source page been deleted?')),
                ('is_validated', models.BooleanField(default=False, help_text='True if both source and target have been validated, confirmed to exist, and source really does link to target.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
