# Generated by Django 3.2.9 on 2021-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingwebmention',
            name='error_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outgoingwebmention',
            name='last_attempt_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
