# Generated by Django 3.2.9 on 2021-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0002_auto_20211126_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingwebmention',
            name='response_code',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
