# Generated by Django 3.2.9 on 2021-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0004_alter_outgoingwebmention_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingwebmention',
            name='status',
            field=models.CharField(choices=[('WA', 'Waiting to be sent'), ('TU', 'Target URL is unreachable'), ('TE', 'Target URL returned an error'), ('EU', 'Endpoint URL is unreachable'), ('EE', 'Endpoint URL returned an error'), ('NE', 'No endpoint found'), ('OK', 'Target accepted the webmention')], default='WA', max_length=2),
        ),
    ]
