# Generated by Django 3.2.9 on 2021-11-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0005_alter_outgoingwebmention_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingwebmention',
            old_name='response_code',
            new_name='endpoint_response_code',
        ),
        migrations.AddField(
            model_name='outgoingwebmention',
            name='target_response_code',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
