virtualbox:
  name: 'Gyford.com'
  memory: '512'
django:
  settings_module: config.settings.vagrant
  run_migrations: 'false'
virtualenv:
  envname: hines
  requirements_file: requirements/vagrant.txt
foreman:
  procfile: Procfile.dev
  start_foreman: 'false'
db:
  name: hines 
  user: hines 
  password: hines 
use_geodjango: 'false'

