INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424987, 'NA', 'Namibia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424897, 'MT', 'Malta', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424968, 'TL', 'Timor-Leste', 'POR', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424956, 'SY', 'Syria', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424758, 'BS', 'The Bahamas', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424944, 'SH', 'St Helena Ascension and Tristan da Cunha', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424902, 'MZ', 'Mozambique', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424744, 'AD', 'Andorra', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23425003, 'ZM', 'Zambia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424921, 'PI', 'Spratly Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424962, 'TC', 'Turks and Caicos Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (20069817, 'ME', 'Montenegro', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424856, 'JP', '日本', 'JPN', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424874, 'LV', 'Latvija', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424822, 'GA', 'Gabon', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424955, 'GS', 'South Georgia and the South Sandwich Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424831, 'GP', 'Guadeloupe', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424997, 'XD', 'United Nations Neutral Zone', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424877, 'SK', 'Slovenská', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424952, 'SD', 'Sudan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424821, 'GM', 'The Gambia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424879, 'LI', 'Liechtenstein', 'GER', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424949, 'SO', 'Somalia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424781, 'CN', '中國', 'CHI', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424808, 'ET', 'Ethiopia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424816, 'FO', 'Føroyar', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424940, 'KN', 'Saint Kitts and Nevis', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424976, 'UA', 'Ukrayina', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424984, 'VN', 'Vietnam', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424870, 'KW', 'Kuwait', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424852, 'IL', 'Israel', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424777, 'TD', 'Chad', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424887, 'MN', 'Mongolia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424963, 'TK', 'Tokelau', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424948, 'SG', 'Singapore', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (28289406, 'TF', 'French Southern Territories', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424941, 'SC', 'Seychelles', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424851, 'IR', 'Iran', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424863, 'KE', 'Kenya', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424871, 'KZ', 'Kazakhstan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424881, 'LU', 'Luxembourg', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424810, 'CZ', 'Ceská Republika', 'CZE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424943, 'SN', 'Sénégal', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424880, 'LS', 'Lesotho', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424942, 'ZA', 'South Africa', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424894, 'MU', 'Mauritius', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424882, 'LY', 'Libya', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424888, 'MS', 'Montserrat', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424741, 'AZ', 'Azerbaijan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424891, 'ML', 'Mali', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424738, 'AE', 'United Arab Emirates', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424864, 'KG', 'Kyrgyzstan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424774, 'BI', 'Burundi', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424737, 'AG', 'Antigua and Barbuda', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424742, 'AL', 'Shqipëri', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424793, 'CU', 'Cuba', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424858, 'JM', 'Jamaica', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424811, 'GF', 'Guyane Française', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424848, 'IN', 'India', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424938, 'SA', 'Saudi Arabia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424890, 'MK', 'Macedonia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424908, 'NG', 'Nigeria', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424854, 'CI', 'Côte d´Ivoire', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424754, 'BB', 'Barbados', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (26812346, 'CY', 'Cyprus', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424989, 'WF', 'Wallis and Futuna', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424931, 'RE', 'La Réunion', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424766, 'SB', 'Solomon Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424932, 'MH', 'Marshall Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424899, 'MV', 'Maldives', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424898, 'OM', 'Oman', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424937, 'RW', 'Rwanda', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424875, 'LT', 'Lietuva', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424978, 'BF', 'Burkina Faso', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424829, 'DE', 'Deutschland', 'GER', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424845, 'IS', 'Ísland', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424844, 'HU', 'Magyarország', 'HUN', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (28289411, 'HM', 'Heard Island and McDonald Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424934, 'PH', 'Philippines', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424981, 'VC', 'Saint Vincent and the Grenadines', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424806, 'ER', 'Eritrea', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424926, 'PG', 'Papua New Guinea', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424929, 'GW', 'Guinea-Bissau', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424945, 'SI', 'Slovenija', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424947, 'SM', 'San Marino', 'ITA', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424925, 'PT', 'Portugal', 'POR', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424928, 'XX', 'Disputed Territory', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424910, 'NO', 'Norge', 'NOR', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424785, 'CM', 'Cameroon', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (20069818, 'RS', 'Serbia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424974, 'UG', 'Uganda', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424865, 'KP', 'North Korea', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424783, 'KY', 'Cayman Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424755, 'BW', 'Botswana', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424918, 'PN', 'Pitcairn Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424775, 'CA', 'Canada', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424819, 'FR', 'France', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424803, 'IE', 'Ireland', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424860, 'JO', 'Jordan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (24865698, 'HK', '香港', 'CHI', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (28289408, 'PS', 'Palestinian Territories', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (56042304, 'BL', 'Saint-Barthélemy', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424917, 'PY', 'Paraguay', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424946, 'SL', 'Sierra Leone', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424788, 'MP', 'Northern Mariana Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424923, 'PL', 'Polska', 'POL', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424782, 'CL', 'Chile', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424784, 'CC', 'Cocos (Keeling) Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424761, 'BA', 'Bosna i Hercegovina', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424939, 'PM', 'Saint Pierre and Miquelon', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424973, 'TZ', 'Tanzania', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424930, 'QA', 'Qatar', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424743, 'AM', 'Armenia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424794, 'CV', 'Cape Verde', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424913, 'SR', 'Suriname', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (56042305, 'MF', 'Saint-Martin', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424791, 'CR', 'Costa Rica', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424736, 'AW', 'Aruba', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424759, 'BD', 'Bangladesh', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424961, 'TJ', 'Tajikistan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424802, 'EG', 'Egypt', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424993, 'SZ', 'Swaziland', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424975, 'GB', 'United Kingdom', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424936, 'RU', 'Rossija', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424776, 'KH', 'Cambodia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424912, 'NR', 'Nauru', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424815, 'FM', 'Federated States of Micronesia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424982, 'VE', 'Venezuela', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424835, 'GN', 'Guinea', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424886, 'YT', 'Mayotte', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424896, 'MR', 'Mauritania', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424849, 'IO', 'British Indian Ocean Territory', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424753, 'BH', 'Bahrain', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424919, 'PE', 'Peru', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424814, 'FK', 'Falkland Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424813, 'FJ', 'Fiji', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424990, 'EH', 'Western Sahara', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424796, 'DK', 'Danmark', 'DAN', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424797, 'DJ', 'Djibouti', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424760, 'BZ', 'Belize', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424985, 'VI', 'US Virgin Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424771, 'BG', 'Bulgaria', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424971, 'TW', '臺灣', 'CHI', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424969, 'TR', 'Turkey', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424853, 'IT', 'Italia', 'ITA', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424757, 'BE', 'België', 'DUT', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (28289409, 'AQ', 'Antarctica', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424798, 'DM', 'Dominica', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424892, 'MC', 'Monaco', 'FRE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424800, 'DO', 'Dominican Republic', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (20070017, 'MO', 'Macau', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424765, 'BY', 'Belarus', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424780, 'CD', 'Democratic Republic of Congo', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424836, 'GY', 'Guyana', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424750, 'AT', 'Österreich', 'GER', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424933, 'RO', 'România', 'RUM', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23425002, 'YE', 'Yemen', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424812, 'FI', 'Suomi', 'FIN', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424905, 'NF', 'Norfolk Island', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424966, 'ST', 'Sao Tome and Principe', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424872, 'LA', 'Laos', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424914, 'AN', 'Netherlands Antilles', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424855, 'IQ', 'Iraq', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424805, 'EE', 'Eesti', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424883, 'MG', 'Madagascar', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424954, 'SE', 'Sverige', 'SWE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424873, 'LB', 'Lebanon', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424992, 'WS', 'Samoa', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424833, 'GR', 'Ellás', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23425004, 'ZW', 'Zimbabwe', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (28289407, 'UM', 'United States Minor Outlying Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424846, 'ID', 'Republik Indonesia', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424834, 'GT', 'Guatemala', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424804, 'GQ', 'Equatorial Guinea', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424900, 'MX', 'México', 'SPA', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424903, 'NC', 'New Caledonia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424916, 'NZ', 'New Zealand', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424927, 'PW', 'Palau', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424970, 'TV', 'Tuvalu', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424965, 'TG', 'Togo', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424998, 'XE', 'Iraq-Saudi Arabia Neutral Zone', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424960, 'TH', 'Thailand', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424817, 'PF', 'French Polynesia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424807, 'SV', 'El Salvador', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424884, 'MQ', 'Martinique', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424786, 'KM', 'Comoros', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (12577865, 'AX', 'Åland', 'SWE', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424843, 'HR', 'Hrvatska', 'UNK', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424740, 'DZ', 'Algeria', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424950, 'ES', 'España', 'SPA', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424746, 'AS', 'American Samoa', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424876, 'LR', 'Liberia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424889, 'MW', 'Malawi', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424869, 'CX', 'Christmas Island', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424828, 'GL', 'Greenland', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424747, 'AR', 'Argentina', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424756, 'BM', 'Bermuda', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424935, 'PR', 'Puerto Rico', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424867, 'KI', 'Kiribati', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424751, 'AI', 'Anguilla', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424906, 'NE', 'Niger', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424792, 'CF', 'Central African Republic', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424748, 'AU', 'Australia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424801, 'EC', 'Ecuador', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424823, 'GE', 'Georgia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424839, 'HT', 'Haiti', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424745, 'AO', 'Angola', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424907, 'VU', 'Vanuatu', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424924, 'PA', 'Panamá', 'SPA', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424826, 'GD', 'Grenada', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424825, 'GI', 'Gibraltar', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424868, 'KR', '한국', 'KOR', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424778, 'LK', 'Sri Lanka', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424983, 'VG', 'British Virgin Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424770, 'BT', 'Bhutan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424922, 'PK', 'Pakistan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424787, 'CO', 'Colombia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424762, 'BO', 'Bolivia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424824, 'GH', 'Ghana', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424795, 'CK', 'Cook Islands', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424885, 'MD', 'Moldova', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424773, 'BN', 'Brunei', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424763, 'MM', 'Myanmar', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (28289413, 'SJ', 'Svalbard and Jan Mayen', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424979, 'UY', 'Uruguay', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424964, 'TO', 'Tonga', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424768, 'BR', 'Brasil', 'POR', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424739, 'AF', 'Afghanistan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424986, 'VA', 'Città del Vaticano', 'ITA', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424901, 'MY', 'Malaysia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424958, 'TT', 'Trinidad and Tobago', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424764, 'BJ', 'Benin', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424909, 'NL', 'Nederland', 'DUT', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424911, 'NP', 'Nepal', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424951, 'LC', 'St. Lucia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424980, 'UZ', 'Uzbekistan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424967, 'TN', 'Tunisia', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424972, 'TM', 'Turkmenistan', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424915, 'NI', 'Nicaragua', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424904, 'NU', 'Niue', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424893, 'MA', 'Morocco', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424957, 'CH', 'Schweiz', 'GER', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424832, 'GU', 'Guam', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (28289410, 'BV', 'Bouvet Island', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424779, 'CG', 'Congo', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424977, 'US', 'United States', 'ENG', 'Country', 1);
INSERT INTO places_place (id, iso, name, language, place_type, parent) VALUES (23424841, 'HN', 'Honduras', 'ENG', 'Country', 1);