# Generated by Django 5.0.4 on 2024-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mastodon_account',
            field=models.CharField(blank=True, help_text='e.g. @Gargron@mastodon.social', max_length=255),
        ),
    ]
