name: test-and-deploy

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Run the tests first:
  use-test:
    uses: philgyford/django-hines/.github/workflows/test.yml@main

  deploy:
    needs: use-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          # The "export PATH..." ensures it picks up the user-installed uv
          script: |
            export PATH="$HOME/.local/bin:$PATH"
            cd /webapps/hines/code
            git checkout .
            git pull
            uv sync --no-dev
            uv run python manage.py migrate
            uv run python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn_hines
            sudo systemctl restart djangoq_hines

      - name: Slack notification
        uses: slackapi/slack-github-action@v4
        if: always()   # Pick up events even if the job fails or is cancelled.
        with:
          webhook: ${{ secrets.ACTIONS_CI_SLACK_HOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: "*Result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}*"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    GitHub Action result: ${{ job.status }}
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    ${{ job.status == 'success' && '✅' || '❌' }} Tests
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    *${{ github.event.pull_request.html_url && 'PR' || 'Commit' }}:* ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    *Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  slack:
    if: always()  # Pick up events even if the job fails or is cancelled.
    runs-on: ubuntu-latest
    needs:
      - use-test
      - deploy

    steps:
      - name: Slack notification
        uses: slackapi/slack-github-action@v4
        with:
          webhook: ${{ secrets.ACTIONS_CI_SLACK_HOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: "*Result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}*"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    GitHub Action result: ${{ job.status }}
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    *${{ needs.use-test.result == 'success' && needs.deploy.result == 'success'
                      && '✅ Every job succeeded' || '❌ One or more jobs failed' }}*

                    ${{ needs.use-test.result == 'success' && '✅' || '❌' }} Tests
                    ${{ needs.deploy.result == 'success' && '✅' || '❌' }} Deploy
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    *${{ github.event.pull_request.html_url && 'PR' || 'Commit' }}:* ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    *Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
